run:
  tests: false
linters:
  enable-all: true
  disable:
    - nosnakecase
    - depguard
    - gofumpt
    - gci
    - wsl
    - wrapcheck
    - structcheck
    - unused
    - forbidigo
    - golint
    - revive
    - whitespace
    - stylecheck
    - sqlclosecheck
    - staticcheck
    - varnamelen
exclude-rules:
  - testpackage
